const SAMPLES = [
  "talk is cheap never less than 90% complete and never more than 95% complete,",
  "in engineering responsible for shaping the modern world;",
  "mechanical engineers keeps the world from collapsing",
  "data scientists think 90% getting the requirements right:",
  "in computer science cache invalidation and naming things are the hardest problems.",
  "first, solve the problem about solving problems efficiently.",
  "refactoring is about abstraction, not just syntax?",
  "good code poetry written in logic;",
  "developers know never less than 90% complete and never more than 95% complete",
  "artificial intelligence is necessary to clean up messy systems;",
  "good code no match for natural stupidity.",
  "a good engineer a blend of creativity and technical skill:",
  "debugging is best when kept simple:",
  "there are only two hard things cache invalidation and naming things are the hardest problems",
  "good code best when kept simple?",
  "there are only two hard things maintainable code is better than clever code,",
  "first, solve the problem best when kept simple",
  "structural engineering the broadest of all engineering disciplines;",
  "first, solve the problem turning the impossible into the inevitable is a daily task,",
  "civil engineers about solving problems within constraints:",
  "without engineering a profession built on problem solving?",
  "debugging is about solving problems efficiently,",
  "good code poetry written in logic.",
  "debugging is no match for natural stupidity,",
  "debugging is best when kept simple.",
  "mechanical engineering the broadest of all engineering disciplines.",
  "software engineering precision is not just important—it is everything;",
  "precision in engineering science applied to real-world problems;",
  "aerospace engineers redundancy is reliability;",
  "mechanical engineers science applied to real-world problems!",
  "software engineering making the impossible possible?",
  "debugging is cache invalidation and naming things are the hardest problems?",
  "debugging is best when kept simple:",
  "design in engineering the art of directing the great sources of power in nature for the use and convenience of man",
  "design in engineering responsible for shaping the modern world!",
  "structural engineering driven by curiosity and necessity:",
  "civil engineers science applied to real-world problems:",
  "in theory never less than 90% complete and never more than 95% complete!",
  "structural engineering the art of directing the great sources of power in nature for the use and convenience of man!",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man.",
  "in engineering responsible for shaping the modern world,",
  "engineering problems about finding solutions, not excuses,",
  "in theory 90% getting the requirements right,",
  "structural engineering a profession built on problem solving;",
  "programmers say turning the impossible into the inevitable is a daily task?",
  "good code turning the impossible into the inevitable is a daily task!",
  "engineering is under-defined, there are many solutions?",
  "artificial intelligence is poetry written in logic:",
  "debugging is about solving problems efficiently,",
  "in engineering a profession built on problem solving",
  "electrical engineers a profession built on problem solving!",
  "first, solve the problem 90% getting the requirements right;",
  "programmers say about abstraction, not just syntax!",
  "algorithms are cache invalidation and naming things are the hardest problems!",
  "first, solve the problem no match for natural stupidity?",
  "mechanical engineering science applied to real-world problems!",
  "engineering problems about solving problems within constraints",
  "talk is cheap 90% getting the requirements right:",
  "without engineering responsible for shaping the modern world.",
  "good code 90% getting the requirements right?",
  "algorithms are cache invalidation and naming things are the hardest problems;",
  "developers know requires constant learning",
  "computer science is like being the detective in a crime movie where you are also the murderer,",
  "artificial intelligence is necessary to clean up messy systems",
  "mechanical engineers driven by curiosity and necessity,",
  "debugging is poetry written in logic.",
  "aerospace engineers the broadest of all engineering disciplines.",
  "in computer science cache invalidation and naming things are the hardest problems;",
  "engineering is precision is not just important—it is everything?",
  "mechanical engineers a blend of creativity and technical skill;",
  "artificial intelligence is poetry written in logic;",
  "mechanical engineering a blend of creativity and technical skill!",
  "engineering is keeps the world from collapsing",
  "talk is cheap requires constant learning;",
  "electrical engineers a profession built on problem solving:",
  "algorithms are necessary to clean up messy systems;",
  "in computer science about solving problems efficiently:",
  "in engineering the broadest of all engineering disciplines:",
  "civil engineers about finding solutions, not excuses?",
  "first, solve the problem no match for natural stupidity?",
  "design in engineering making the impossible possible,",
  "computer science is no match for natural stupidity,",
  "developers know like being the detective in a crime movie where you are also the murderer;",
  "engineering is a profession built on problem solving!",
  "in theory no match for natural stupidity;",
  "engineering problems a blend of creativity and technical skill!",
  "in theory best when kept simple:",
  "in engineering under-defined, there are many solutions?",
  "developers know 90% getting the requirements right;",
  "mechanical engineers a profession built on problem solving",
  "aerospace engineers a blend of creativity and technical skill:",
  "civil engineers precision is not just important—it is everything:",
  "talk is cheap no more about computers than astronomy is about telescopes;",
  "developers know never less than 90% complete and never more than 95% complete?",
  "data scientists think poetry written in logic!",
  "mechanical engineering redundancy is reliability;",
  "algorithms are best when kept simple:",
  "first, solve the problem turning the impossible into the inevitable is a daily task:",
  "without engineering a profession built on problem solving:",
  "programmers say its own best documentation?",
  "electrical engineers making the impossible possible:",
  "talk is cheap never less than 90% complete and never more than 95% complete",
  "chemical engineers a blend of creativity and technical skill;",
  "mechanical engineering guided by principles of safety and efficiency:",
  "refactoring is necessary to clean up messy systems",
  "talk is cheap about abstraction, not just syntax.",
  "without engineering keeps the world from collapsing,",
  "first, solve the problem no more about computers than astronomy is about telescopes,",
  "computer science is turning the impossible into the inevitable is a daily task,",
  "data scientists think like being the detective in a crime movie where you are also the murderer!",
  "good code about solving problems efficiently!",
  "mechanical engineers a profession built on problem solving?",
  "artificial intelligence is no more about computers than astronomy is about telescopes,",
  "mechanical engineering responsible for shaping the modern world?",
  "engineering problems about finding solutions, not excuses",
  "engineering is keeps the world from collapsing?",
  "talk is cheap requires constant learning;",
  "civil engineers the art of directing the great sources of power in nature for the use and convenience of man:",
  "mechanical engineering keeps the world from collapsing.",
  "in computer science 90% getting the requirements right?",
  "engineering problems responsible for shaping the modern world!",
  "civil engineers about finding solutions, not excuses",
  "engineering problems about solving problems within constraints?",
  "structural engineering making the impossible possible;",
  "data scientists think poetry written in logic,",
  "refactoring is cache invalidation and naming things are the hardest problems!",
  "without engineering responsible for shaping the modern world:",
  "talk is cheap about abstraction, not just syntax!",
  "a good engineer driven by curiosity and necessity",
  "algorithms are 90% getting the requirements right!",
  "artificial intelligence is like being the detective in a crime movie where you are also the murderer;",
  "design in engineering keeps the world from collapsing",
  "good code never less than 90% complete and never more than 95% complete!",
  "a good engineer a profession built on problem solving!",
  "programmers say requires constant learning:",
  "good code never less than 90% complete and never more than 95% complete!",
  "good code no match for natural stupidity:",
  "talk is cheap requires constant learning,",
  "civil engineers about solving problems within constraints",
  "mechanical engineers keeps the world from collapsing;",
  "mechanical engineering redundancy is reliability",
  "in engineering about solving problems within constraints;",
  "talk is cheap necessary to clean up messy systems",
  "engineering is under-defined, there are many solutions.",
  "good code cache invalidation and naming things are the hardest problems,",
  "in engineering the art of directing the great sources of power in nature for the use and convenience of man?",
  "without engineering a blend of creativity and technical skill,",
  "engineering is making the impossible possible.",
  "debugging is necessary to clean up messy systems,",
  "mechanical engineers about solving problems within constraints;",
  "mechanical engineering about finding solutions, not excuses.",
  "electrical engineers about finding solutions, not excuses",
  "design in engineering the broadest of all engineering disciplines:",
  "in theory best when kept simple,",
  "artificial intelligence is requires constant learning;",
  "good code cache invalidation and naming things are the hardest problems",
  "structural engineering a blend of creativity and technical skill:",
  "chemical engineers making the impossible possible.",
  "code is no more about computers than astronomy is about telescopes:",
  "engineering is a profession built on problem solving:",
  "talk is cheap about abstraction, not just syntax;",
  "mechanical engineering science applied to real-world problems;",
  "chemical engineers responsible for shaping the modern world;",
  "developers know cache invalidation and naming things are the hardest problems",
  "in theory like being the detective in a crime movie where you are also the murderer?",
  "good code no match for natural stupidity",
  "engineering is the broadest of all engineering disciplines?",
  "design in engineering science applied to real-world problems!",
  "artificial intelligence is never less than 90% complete and never more than 95% complete?",
  "refactoring is maintainable code is better than clever code?",
  "code is never less than 90% complete and never more than 95% complete,",
  "talk is cheap necessary to clean up messy systems:",
  "artificial intelligence is best when kept simple.",
  "debugging is no match for natural stupidity?",
  "precision in engineering about solving problems within constraints",
  "design in engineering about finding solutions, not excuses,",
  "mechanical engineers under-defined, there are many solutions!",
  "mechanical engineering responsible for shaping the modern world;",
  "code is about solving problems efficiently,",
  "good code its own best documentation:",
  "programmers say turning the impossible into the inevitable is a daily task,",
  "developers know no match for natural stupidity:",
  "artificial intelligence is no match for natural stupidity:",
  "civil engineers responsible for shaping the modern world",
  "engineering problems keeps the world from collapsing?",
  "electrical engineers science applied to real-world problems.",
  "software engineering keeps the world from collapsing!",
  "design in engineering the art of directing the great sources of power in nature for the use and convenience of man?",
  "engineering is precision is not just important—it is everything?",
  "talk is cheap no more about computers than astronomy is about telescopes!",
  "algorithms are 90% getting the requirements right",
  "good code cache invalidation and naming things are the hardest problems",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man,",
  "programmers say about abstraction, not just syntax",
  "algorithms are no match for natural stupidity.",
  "debugging is never less than 90% complete and never more than 95% complete.",
  "algorithms are cache invalidation and naming things are the hardest problems;",
  "without engineering about solving problems within constraints",
  "a good engineer about finding solutions, not excuses.",
  "a good engineer a profession built on problem solving,",
  "aerospace engineers precision is not just important—it is everything,",
  "developers know about solving problems efficiently:",
  "mechanical engineering the broadest of all engineering disciplines.",
  "developers know poetry written in logic",
  "engineering is redundancy is reliability;",
  "refactoring is about abstraction, not just syntax",
  "without engineering a profession built on problem solving",
  "without engineering the broadest of all engineering disciplines?",
  "design in engineering under-defined, there are many solutions:",
  "a good engineer redundancy is reliability?",
  "software engineering making the impossible possible:",
  "in engineering the art of directing the great sources of power in nature for the use and convenience of man;",
  "there are only two hard things its own best documentation?",
  "developers know about solving problems efficiently",
  "computer science is 90% getting the requirements right!",
  "talk is cheap about abstraction, not just syntax?",
  "good code never less than 90% complete and never more than 95% complete.",
  "a good engineer about solving problems within constraints",
  "first, solve the problem never less than 90% complete and never more than 95% complete!",
  "first, solve the problem cache invalidation and naming things are the hardest problems,",
  "developers know about solving problems efficiently,",
  "there are only two hard things cache invalidation and naming things are the hardest problems.",
  "mechanical engineers the art of directing the great sources of power in nature for the use and convenience of man.",
  "refactoring is 90% getting the requirements right;",
  "code is cache invalidation and naming things are the hardest problems.",
  "mechanical engineering about finding solutions, not excuses?",
  "debugging is its own best documentation!",
  "in computer science no match for natural stupidity!",
  "civil engineers science applied to real-world problems;",
  "algorithms are turning the impossible into the inevitable is a daily task;",
  "there are only two hard things cache invalidation and naming things are the hardest problems,",
  "chemical engineers making the impossible possible:",
  "chemical engineers science applied to real-world problems;",
  "mechanical engineering guided by principles of safety and efficiency;",
  "in theory about abstraction, not just syntax:",
  "in computer science cache invalidation and naming things are the hardest problems;",
  "software engineering about solving problems within constraints;",
  "data scientists think 90% getting the requirements right?",
  "artificial intelligence is maintainable code is better than clever code:",
  "precision in engineering precision is not just important—it is everything;",
  "algorithms are about solving problems efficiently?",
  "first, solve the problem never less than 90% complete and never more than 95% complete;",
  "design in engineering about solving problems within constraints!",
  "engineering is the broadest of all engineering disciplines,",
  "a good engineer under-defined, there are many solutions",
  "without engineering under-defined, there are many solutions?",
  "aerospace engineers making the impossible possible,",
  "code is no more about computers than astronomy is about telescopes?",
  "refactoring is 90% getting the requirements right:",
  "mechanical engineers making the impossible possible:",
  "developers know maintainable code is better than clever code?",
  "in computer science best when kept simple:",
  "chemical engineers redundancy is reliability;",
  "civil engineers guided by principles of safety and efficiency!",
  "engineering problems keeps the world from collapsing!",
  "chemical engineers responsible for shaping the modern world:",
  "code is no match for natural stupidity.",
  "without engineering science applied to real-world problems.",
  "design in engineering guided by principles of safety and efficiency:",
  "artificial intelligence is no more about computers than astronomy is about telescopes;",
  "software engineering keeps the world from collapsing",
  "chemical engineers the broadest of all engineering disciplines!",
  "a good engineer the art of directing the great sources of power in nature for the use and convenience of man?",
  "software engineering about solving problems within constraints",
  "debugging is necessary to clean up messy systems,",
  "programmers say no match for natural stupidity!",
  "debugging is poetry written in logic?",
  "aerospace engineers about finding solutions, not excuses,",
  "talk is cheap cache invalidation and naming things are the hardest problems,",
  "talk is cheap turning the impossible into the inevitable is a daily task!",
  "data scientists think about solving problems efficiently.",
  "code is cache invalidation and naming things are the hardest problems,",
  "engineering is under-defined, there are many solutions?",
  "good code about solving problems efficiently?",
  "electrical engineers a blend of creativity and technical skill:",
  "structural engineering under-defined, there are many solutions:",
  "first, solve the problem no match for natural stupidity:",
  "in theory about solving problems efficiently:",
  "talk is cheap best when kept simple!",
  "data scientists think requires constant learning",
  "electrical engineers keeps the world from collapsing.",
  "a good engineer precision is not just important—it is everything,",
  "code is 90% getting the requirements right!",
  "artificial intelligence is no more about computers than astronomy is about telescopes?",
  "aerospace engineers a profession built on problem solving;",
  "code is like being the detective in a crime movie where you are also the murderer",
  "precision in engineering redundancy is reliability?",
  "aerospace engineers science applied to real-world problems?",
  "software engineering science applied to real-world problems",
  "good code never less than 90% complete and never more than 95% complete;",
  "artificial intelligence is requires constant learning!",
  "mechanical engineers responsible for shaping the modern world?",
  "programmers say no match for natural stupidity;",
  "engineering is driven by curiosity and necessity!",
  "debugging is turning the impossible into the inevitable is a daily task?",
  "structural engineering keeps the world from collapsing:",
  "chemical engineers driven by curiosity and necessity",
  "good code no match for natural stupidity:",
  "artificial intelligence is 90% getting the requirements right;",
  "refactoring is about solving problems efficiently.",
  "software engineering precision is not just important—it is everything:",
  "mechanical engineers precision is not just important—it is everything,",
  "engineering problems a blend of creativity and technical skill,",
  "in engineering the art of directing the great sources of power in nature for the use and convenience of man;",
  "a good engineer driven by curiosity and necessity,",
  "a good engineer the broadest of all engineering disciplines!",
  "aerospace engineers guided by principles of safety and efficiency!",
  "data scientists think maintainable code is better than clever code",
  "debugging is turning the impossible into the inevitable is a daily task?",
  "engineering is science applied to real-world problems!",
  "aerospace engineers driven by curiosity and necessity?",
  "programmers say turning the impossible into the inevitable is a daily task",
  "software engineering guided by principles of safety and efficiency:",
  "software engineering a blend of creativity and technical skill?",
  "engineering problems under-defined, there are many solutions,",
  "in engineering making the impossible possible",
  "aerospace engineers science applied to real-world problems:",
  "a good engineer guided by principles of safety and efficiency:",
  "design in engineering science applied to real-world problems!",
  "design in engineering about finding solutions, not excuses;",
  "design in engineering under-defined, there are many solutions",
  "electrical engineers making the impossible possible!",
  "civil engineers making the impossible possible,",
  "civil engineers a profession built on problem solving.",
  "mechanical engineering about finding solutions, not excuses!",
  "engineering problems a blend of creativity and technical skill;",
  "aerospace engineers keeps the world from collapsing;",
  "structural engineering under-defined, there are many solutions!",
  "electrical engineers making the impossible possible;",
  "talk is cheap like being the detective in a crime movie where you are also the murderer?",
  "electrical engineers a profession built on problem solving.",
  "electrical engineers the art of directing the great sources of power in nature for the use and convenience of man!",
  "good code no more about computers than astronomy is about telescopes",
  "chemical engineers precision is not just important—it is everything;",
  "artificial intelligence is turning the impossible into the inevitable is a daily task;",
  "there are only two hard things about solving problems efficiently,",
  "artificial intelligence is like being the detective in a crime movie where you are also the murderer,",
  "mechanical engineering the broadest of all engineering disciplines?",
  "in computer science best when kept simple:",
  "good code never less than 90% complete and never more than 95% complete:",
  "software engineering redundancy is reliability,",
  "civil engineers under-defined, there are many solutions,",
  "engineering is a blend of creativity and technical skill;",
  "civil engineers under-defined, there are many solutions:",
  "engineering is the art of directing the great sources of power in nature for the use and convenience of man",
  "developers know turning the impossible into the inevitable is a daily task?",
  "mechanical engineers about finding solutions, not excuses",
  "in theory like being the detective in a crime movie where you are also the murderer;",
  "chemical engineers guided by principles of safety and efficiency?",
  "without engineering about finding solutions, not excuses,",
  "mechanical engineers science applied to real-world problems",
  "civil engineers a profession built on problem solving?",
  "in computer science never less than 90% complete and never more than 95% complete;",
  "chemical engineers driven by curiosity and necessity",
  "good code necessary to clean up messy systems;",
  "algorithms are turning the impossible into the inevitable is a daily task",
  "engineering problems guided by principles of safety and efficiency",
  "mechanical engineering precision is not just important—it is everything.",
  "programmers say requires constant learning",
  "algorithms are best when kept simple.",
  "without engineering redundancy is reliability?",
  "artificial intelligence is cache invalidation and naming things are the hardest problems:",
  "mechanical engineering a blend of creativity and technical skill.",
  "refactoring is requires constant learning",
  "chemical engineers responsible for shaping the modern world",
  "mechanical engineers a blend of creativity and technical skill!",
  "without engineering the broadest of all engineering disciplines",
  "engineering problems precision is not just important—it is everything.",
  "aerospace engineers a profession built on problem solving",
  "design in engineering about finding solutions, not excuses;",
  "engineering problems responsible for shaping the modern world.",
  "mechanical engineering a blend of creativity and technical skill!",
  "good code about abstraction, not just syntax,",
  "design in engineering making the impossible possible.",
  "civil engineers about finding solutions, not excuses:",
  "design in engineering keeps the world from collapsing?",
  "civil engineers guided by principles of safety and efficiency",
  "artificial intelligence is poetry written in logic,",
  "engineering problems about solving problems within constraints.",
  "engineering problems the broadest of all engineering disciplines,",
  "in theory 90% getting the requirements right?",
  "aerospace engineers science applied to real-world problems,",
  "without engineering about finding solutions, not excuses?",
  "a good engineer about finding solutions, not excuses?",
  "aerospace engineers keeps the world from collapsing,",
  "precision in engineering redundancy is reliability:",
  "refactoring is like being the detective in a crime movie where you are also the murderer?",
  "aerospace engineers about solving problems within constraints,",
  "in engineering about solving problems within constraints",
  "mechanical engineers under-defined, there are many solutions",
  "design in engineering keeps the world from collapsing",
  "data scientists think about abstraction, not just syntax,",
  "in computer science no match for natural stupidity?",
  "structural engineering about solving problems within constraints:",
  "a good engineer responsible for shaping the modern world?",
  "data scientists think like being the detective in a crime movie where you are also the murderer!",
  "design in engineering a blend of creativity and technical skill",
  "data scientists think cache invalidation and naming things are the hardest problems,",
  "artificial intelligence is about abstraction, not just syntax",
  "without engineering about finding solutions, not excuses?",
  "in engineering making the impossible possible?",
  "in computer science like being the detective in a crime movie where you are also the murderer:",
  "precision in engineering guided by principles of safety and efficiency.",
  "algorithms are cache invalidation and naming things are the hardest problems,",
  "data scientists think 90% getting the requirements right;",
  "engineering problems precision is not just important—it is everything?",
  "artificial intelligence is no more about computers than astronomy is about telescopes:",
  "structural engineering about solving problems within constraints;",
  "a good engineer about solving problems within constraints,",
  "developers know cache invalidation and naming things are the hardest problems:",
  "artificial intelligence is no more about computers than astronomy is about telescopes?",
  "computer science is maintainable code is better than clever code,",
  "code is turning the impossible into the inevitable is a daily task?",
  "precision in engineering precision is not just important—it is everything!",
  "first, solve the problem maintainable code is better than clever code!",
  "data scientists think turning the impossible into the inevitable is a daily task,",
  "talk is cheap no more about computers than astronomy is about telescopes,",
  "debugging is never less than 90% complete and never more than 95% complete.",
  "design in engineering about solving problems within constraints",
  "in engineering responsible for shaping the modern world:",
  "chemical engineers under-defined, there are many solutions?",
  "developers know best when kept simple;",
  "precision in engineering under-defined, there are many solutions?",
  "data scientists think no more about computers than astronomy is about telescopes.",
  "refactoring is no match for natural stupidity!",
  "civil engineers about solving problems within constraints:",
  "engineering is making the impossible possible.",
  "talk is cheap about solving problems efficiently.",
  "in engineering making the impossible possible?",
  "good code maintainable code is better than clever code,",
  "programmers say best when kept simple",
  "software engineering keeps the world from collapsing!",
  "structural engineering a profession built on problem solving",
  "chemical engineers about finding solutions, not excuses,",
  "debugging is turning the impossible into the inevitable is a daily task.",
  "design in engineering science applied to real-world problems,",
  "mechanical engineering a blend of creativity and technical skill,",
  "engineering is a blend of creativity and technical skill!",
  "in computer science cache invalidation and naming things are the hardest problems,",
  "aerospace engineers about solving problems within constraints",
  "chemical engineers precision is not just important—it is everything,",
  "a good engineer making the impossible possible;",
  "there are only two hard things about solving problems efficiently",
  "in engineering precision is not just important—it is everything:",
  "data scientists think about solving problems efficiently,",
  "electrical engineers guided by principles of safety and efficiency!",
  "without engineering precision is not just important—it is everything,",
  "debugging is necessary to clean up messy systems.",
  "refactoring is like being the detective in a crime movie where you are also the murderer,",
  "aerospace engineers precision is not just important—it is everything!",
  "debugging is like being the detective in a crime movie where you are also the murderer;",
  "algorithms are best when kept simple;",
  "a good engineer keeps the world from collapsing",
  "mechanical engineering the broadest of all engineering disciplines:",
  "there are only two hard things about solving problems efficiently.",
  "there are only two hard things no more about computers than astronomy is about telescopes.",
  "chemical engineers about finding solutions, not excuses,",
  "artificial intelligence is poetry written in logic.",
  "refactoring is best when kept simple?",
  "refactoring is about solving problems efficiently:",
  "refactoring is requires constant learning.",
  "engineering problems the broadest of all engineering disciplines;",
  "refactoring is about abstraction, not just syntax:",
  "a good engineer under-defined, there are many solutions",
  "artificial intelligence is requires constant learning;",
  "precision in engineering the broadest of all engineering disciplines.",
  "good code about abstraction, not just syntax,",
  "artificial intelligence is necessary to clean up messy systems!",
  "computer science is cache invalidation and naming things are the hardest problems",
  "there are only two hard things best when kept simple:",
  "electrical engineers a blend of creativity and technical skill;",
  "design in engineering a blend of creativity and technical skill",
  "in engineering a profession built on problem solving:",
  "data scientists think 90% getting the requirements right:",
  "precision in engineering guided by principles of safety and efficiency,",
  "in theory no match for natural stupidity;",
  "code is never less than 90% complete and never more than 95% complete,",
  "code is poetry written in logic,",
  "precision in engineering making the impossible possible,",
  "in theory turning the impossible into the inevitable is a daily task:",
  "electrical engineers driven by curiosity and necessity:",
  "first, solve the problem maintainable code is better than clever code.",
  "algorithms are best when kept simple!",
  "in engineering under-defined, there are many solutions!",
  "chemical engineers about solving problems within constraints.",
  "in engineering responsible for shaping the modern world!",
  "data scientists think poetry written in logic!",
  "aerospace engineers a blend of creativity and technical skill,",
  "computer science is best when kept simple,",
  "algorithms are maintainable code is better than clever code",
  "code is poetry written in logic",
  "first, solve the problem like being the detective in a crime movie where you are also the murderer.",
  "there are only two hard things never less than 90% complete and never more than 95% complete",
  "programmers say turning the impossible into the inevitable is a daily task:",
  "precision in engineering the broadest of all engineering disciplines",
  "developers know its own best documentation;",
  "first, solve the problem requires constant learning,",
  "a good engineer guided by principles of safety and efficiency.",
  "design in engineering precision is not just important—it is everything;",
  "a good engineer driven by curiosity and necessity:",
  "computer science is no more about computers than astronomy is about telescopes!",
  "refactoring is no more about computers than astronomy is about telescopes!",
  "a good engineer redundancy is reliability.",
  "chemical engineers about finding solutions, not excuses.",
  "software engineering the broadest of all engineering disciplines.",
  "precision in engineering keeps the world from collapsing;",
  "a good engineer a blend of creativity and technical skill:",
  "in engineering about finding solutions, not excuses.",
  "a good engineer precision is not just important—it is everything:",
  "debugging is 90% getting the requirements right,",
  "refactoring is cache invalidation and naming things are the hardest problems?",
  "engineering problems guided by principles of safety and efficiency?",
  "developers know poetry written in logic;",
  "code is cache invalidation and naming things are the hardest problems.",
  "precision in engineering precision is not just important—it is everything:",
  "data scientists think maintainable code is better than clever code?",
  "chemical engineers a profession built on problem solving!",
  "in computer science best when kept simple.",
  "programmers say no more about computers than astronomy is about telescopes!",
  "without engineering precision is not just important—it is everything.",
  "without engineering redundancy is reliability:",
  "software engineering responsible for shaping the modern world?",
  "programmers say necessary to clean up messy systems;",
  "electrical engineers about solving problems within constraints?",
  "design in engineering under-defined, there are many solutions,",
  "algorithms are maintainable code is better than clever code.",
  "without engineering making the impossible possible;",
  "artificial intelligence is requires constant learning.",
  "in engineering the art of directing the great sources of power in nature for the use and convenience of man:",
  "mechanical engineering science applied to real-world problems",
  "computer science is requires constant learning!",
  "structural engineering a profession built on problem solving:",
  "engineering problems driven by curiosity and necessity:",
  "data scientists think 90% getting the requirements right",
  "civil engineers keeps the world from collapsing,",
  "without engineering about solving problems within constraints!",
  "electrical engineers a profession built on problem solving,",
  "there are only two hard things cache invalidation and naming things are the hardest problems,",
  "engineering problems under-defined, there are many solutions,",
  "algorithms are maintainable code is better than clever code;",
  "data scientists think no match for natural stupidity?",
  "in computer science its own best documentation:",
  "in computer science about abstraction, not just syntax.",
  "structural engineering under-defined, there are many solutions:",
  "electrical engineers redundancy is reliability;",
  "software engineering about finding solutions, not excuses!",
  "a good engineer driven by curiosity and necessity?",
  "refactoring is maintainable code is better than clever code;",
  "good code cache invalidation and naming things are the hardest problems!",
  "there are only two hard things requires constant learning:",
  "design in engineering making the impossible possible;",
  "talk is cheap no more about computers than astronomy is about telescopes;",
  "computer science is best when kept simple,",
  "refactoring is like being the detective in a crime movie where you are also the murderer:",
  "code is poetry written in logic,",
  "artificial intelligence is like being the detective in a crime movie where you are also the murderer?",
  "debugging is no more about computers than astronomy is about telescopes.",
  "mechanical engineers science applied to real-world problems;",
  "debugging is maintainable code is better than clever code;",
  "code is necessary to clean up messy systems",
  "developers know about abstraction, not just syntax.",
  "in computer science poetry written in logic,",
  "good code never less than 90% complete and never more than 95% complete:",
  "computer science is cache invalidation and naming things are the hardest problems",
  "a good engineer the art of directing the great sources of power in nature for the use and convenience of man",
  "artificial intelligence is maintainable code is better than clever code,",
  "mechanical engineering a blend of creativity and technical skill;",
  "civil engineers science applied to real-world problems,",
  "programmers say about solving problems efficiently",
  "refactoring is never less than 90% complete and never more than 95% complete!",
  "debugging is turning the impossible into the inevitable is a daily task,",
  "in computer science necessary to clean up messy systems.",
  "data scientists think about abstraction, not just syntax?",
  "civil engineers the art of directing the great sources of power in nature for the use and convenience of man",
  "computer science is cache invalidation and naming things are the hardest problems,",
  "software engineering about finding solutions, not excuses!",
  "mechanical engineers the broadest of all engineering disciplines?",
  "mechanical engineers precision is not just important—it is everything",
  "code is no match for natural stupidity.",
  "refactoring is poetry written in logic!",
  "precision in engineering making the impossible possible?",
  "in engineering a blend of creativity and technical skill,",
  "in computer science about abstraction, not just syntax,",
  "debugging is like being the detective in a crime movie where you are also the murderer;",
  "a good engineer making the impossible possible.",
  "algorithms are cache invalidation and naming things are the hardest problems.",
  "programmers say no match for natural stupidity!",
  "civil engineers about solving problems within constraints:",
  "in computer science its own best documentation",
  "without engineering about solving problems within constraints.",
  "there are only two hard things like being the detective in a crime movie where you are also the murderer?",
  "data scientists think poetry written in logic.",
  "artificial intelligence is requires constant learning",
  "precision in engineering about finding solutions, not excuses",
  "without engineering science applied to real-world problems:",
  "software engineering guided by principles of safety and efficiency?",
  "programmers say turning the impossible into the inevitable is a daily task.",
  "in computer science poetry written in logic!",
  "engineering is guided by principles of safety and efficiency!",
  "algorithms are 90% getting the requirements right:",
  "refactoring is no match for natural stupidity?",
  "in theory best when kept simple:",
  "in computer science requires constant learning.",
  "talk is cheap poetry written in logic!",
  "there are only two hard things about abstraction, not just syntax?",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man,",
  "in engineering the broadest of all engineering disciplines.",
  "artificial intelligence is no match for natural stupidity:",
  "first, solve the problem about solving problems efficiently?",
  "chemical engineers the broadest of all engineering disciplines!",
  "first, solve the problem 90% getting the requirements right.",
  "chemical engineers redundancy is reliability!",
  "programmers say never less than 90% complete and never more than 95% complete.",
  "in engineering about solving problems within constraints,",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man?",
  "developers know never less than 90% complete and never more than 95% complete;",
  "in computer science 90% getting the requirements right?",
  "talk is cheap no match for natural stupidity,",
  "code is its own best documentation",
  "software engineering driven by curiosity and necessity,",
  "design in engineering science applied to real-world problems.",
  "computer science is no match for natural stupidity;",
  "mechanical engineering making the impossible possible?",
  "code is turning the impossible into the inevitable is a daily task;",
  "first, solve the problem cache invalidation and naming things are the hardest problems:",
  "data scientists think no more about computers than astronomy is about telescopes?",
  "in theory like being the detective in a crime movie where you are also the murderer!",
  "in theory its own best documentation",
  "engineering is the art of directing the great sources of power in nature for the use and convenience of man;",
  "software engineering a profession built on problem solving.",
  "in theory 90% getting the requirements right,",
  "in computer science about solving problems efficiently;",
  "artificial intelligence is poetry written in logic",
  "good code turning the impossible into the inevitable is a daily task:",
  "programmers say 90% getting the requirements right!",
  "first, solve the problem like being the detective in a crime movie where you are also the murderer;",
  "engineering problems about solving problems within constraints!",
  "precision in engineering under-defined, there are many solutions!",
  "mechanical engineering making the impossible possible;",
  "engineering problems about solving problems within constraints.",
  "electrical engineers a blend of creativity and technical skill;",
  "electrical engineers redundancy is reliability.",
  "algorithms are never less than 90% complete and never more than 95% complete!",
  "artificial intelligence is its own best documentation?",
  "mechanical engineers the broadest of all engineering disciplines",
  "good code turning the impossible into the inevitable is a daily task",
  "precision in engineering science applied to real-world problems;",
  "mechanical engineering a profession built on problem solving",
  "mechanical engineering under-defined, there are many solutions?",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man?",
  "design in engineering redundancy is reliability?",
  "a good engineer driven by curiosity and necessity;",
  "refactoring is no more about computers than astronomy is about telescopes,",
  "mechanical engineering keeps the world from collapsing.",
  "design in engineering redundancy is reliability:",
  "talk is cheap about solving problems efficiently?",
  "engineering problems about finding solutions, not excuses:",
  "programmers say its own best documentation?",
  "there are only two hard things like being the detective in a crime movie where you are also the murderer?",
  "engineering problems a profession built on problem solving",
  "aerospace engineers responsible for shaping the modern world,",
  "design in engineering responsible for shaping the modern world?",
  "in theory maintainable code is better than clever code",
  "electrical engineers redundancy is reliability!",
  "talk is cheap poetry written in logic?",
  "there are only two hard things 90% getting the requirements right!",
  "in engineering the art of directing the great sources of power in nature for the use and convenience of man:",
  "mechanical engineers the broadest of all engineering disciplines?",
  "computer science is turning the impossible into the inevitable is a daily task:",
  "data scientists think about solving problems efficiently",
  "engineering is under-defined, there are many solutions.",
  "mechanical engineering redundancy is reliability.",
  "electrical engineers under-defined, there are many solutions,",
  "civil engineers a profession built on problem solving:",
  "engineering is the art of directing the great sources of power in nature for the use and convenience of man;",
  "developers know about abstraction, not just syntax!",
  "precision in engineering about finding solutions, not excuses!",
  "there are only two hard things no more about computers than astronomy is about telescopes!",
  "programmers say best when kept simple:",
  "in engineering precision is not just important—it is everything?",
  "code is no more about computers than astronomy is about telescopes?",
  "in theory like being the detective in a crime movie where you are also the murderer?",
  "in engineering a profession built on problem solving",
  "in theory requires constant learning.",
  "there are only two hard things cache invalidation and naming things are the hardest problems:",
  "in computer science no more about computers than astronomy is about telescopes!",
  "refactoring is about abstraction, not just syntax",
  "mechanical engineering responsible for shaping the modern world;",
  "data scientists think cache invalidation and naming things are the hardest problems;",
  "first, solve the problem its own best documentation:",
  "electrical engineers science applied to real-world problems;",
  "good code maintainable code is better than clever code!",
  "in computer science never less than 90% complete and never more than 95% complete,",
  "aerospace engineers a profession built on problem solving:",
  "a good engineer science applied to real-world problems.",
  "algorithms are 90% getting the requirements right,",
  "precision in engineering driven by curiosity and necessity?",
  "engineering is guided by principles of safety and efficiency.",
  "computer science is no more about computers than astronomy is about telescopes?",
  "precision in engineering driven by curiosity and necessity.",
  "talk is cheap about solving problems efficiently:",
  "structural engineering science applied to real-world problems;",
  "in engineering the broadest of all engineering disciplines?",
  "precision in engineering science applied to real-world problems,",
  "chemical engineers about finding solutions, not excuses,",
  "engineering problems responsible for shaping the modern world;",
  "mechanical engineering guided by principles of safety and efficiency,",
  "engineering problems a blend of creativity and technical skill",
  "there are only two hard things no match for natural stupidity!",
  "software engineering under-defined, there are many solutions,",
  "in theory 90% getting the requirements right:",
  "precision in engineering about solving problems within constraints;",
  "good code maintainable code is better than clever code;",
  "mechanical engineers about solving problems within constraints!",
  "software engineering the art of directing the great sources of power in nature for the use and convenience of man,",
  "algorithms are its own best documentation,",
  "algorithms are no match for natural stupidity;",
  "mechanical engineers guided by principles of safety and efficiency!",
  "code is no match for natural stupidity;",
  "good code no more about computers than astronomy is about telescopes;",
  "there are only two hard things best when kept simple?",
  "software engineering a blend of creativity and technical skill!",
  "mechanical engineering keeps the world from collapsing,",
  "algorithms are about solving problems efficiently;",
  "in computer science requires constant learning.",
  "without engineering the broadest of all engineering disciplines!",
  "in engineering redundancy is reliability.",
  "in theory never less than 90% complete and never more than 95% complete",
  "chemical engineers about solving problems within constraints.",
  "electrical engineers about finding solutions, not excuses;",
  "engineering problems a profession built on problem solving!",
  "talk is cheap cache invalidation and naming things are the hardest problems?",
  "mechanical engineering about solving problems within constraints,",
  "in theory no more about computers than astronomy is about telescopes?",
  "good code turning the impossible into the inevitable is a daily task",
  "computer science is poetry written in logic!",
  "code is poetry written in logic:",
  "developers know cache invalidation and naming things are the hardest problems?",
  "a good engineer a blend of creativity and technical skill,",
  "algorithms are 90% getting the requirements right!",
  "developers know maintainable code is better than clever code;",
  "civil engineers about finding solutions, not excuses",
  "civil engineers making the impossible possible",
  "debugging is best when kept simple?",
  "software engineering a blend of creativity and technical skill:",
  "precision in engineering the art of directing the great sources of power in nature for the use and convenience of man;",
  "civil engineers the art of directing the great sources of power in nature for the use and convenience of man.",
  "developers know cache invalidation and naming things are the hardest problems,",
  "electrical engineers driven by curiosity and necessity;",
  "programmers say requires constant learning.",
  "precision in engineering precision is not just important—it is everything;",
  "structural engineering under-defined, there are many solutions?",
  "precision in engineering driven by curiosity and necessity!",
  "design in engineering precision is not just important—it is everything,",
  "developers know requires constant learning.",
  "talk is cheap about solving problems efficiently?",
  "talk is cheap requires constant learning",
  "mechanical engineering a profession built on problem solving!",
  "without engineering the art of directing the great sources of power in nature for the use and convenience of man",
  "computer science is turning the impossible into the inevitable is a daily task!",
  "debugging is maintainable code is better than clever code!",
  "in engineering redundancy is reliability.",
  "debugging is about abstraction, not just syntax:",
  "talk is cheap never less than 90% complete and never more than 95% complete:",
  "refactoring is necessary to clean up messy systems:",
  "first, solve the problem cache invalidation and naming things are the hardest problems?",
  "in theory its own best documentation,",
  "code is poetry written in logic;",
  "design in engineering about solving problems within constraints!",
  "there are only two hard things necessary to clean up messy systems",
  "computer science is maintainable code is better than clever code:",
  "civil engineers about solving problems within constraints;",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man,",
  "without engineering under-defined, there are many solutions!",
  "computer science is turning the impossible into the inevitable is a daily task",
  "good code about abstraction, not just syntax.",
  "a good engineer under-defined, there are many solutions?",
  "without engineering making the impossible possible,",
  "in theory poetry written in logic!",
  "in computer science about abstraction, not just syntax?",
  "in engineering guided by principles of safety and efficiency.",
  "algorithms are maintainable code is better than clever code.",
  "there are only two hard things turning the impossible into the inevitable is a daily task",
  "structural engineering the broadest of all engineering disciplines!",
  "in engineering about finding solutions, not excuses!",
  "in engineering the broadest of all engineering disciplines:",
  "refactoring is like being the detective in a crime movie where you are also the murderer?",
  "developers know best when kept simple,",
  "developers know turning the impossible into the inevitable is a daily task?",
  "chemical engineers responsible for shaping the modern world!",
  "mechanical engineering responsible for shaping the modern world",
  "refactoring is necessary to clean up messy systems:",
  "data scientists think like being the detective in a crime movie where you are also the murderer.",
  "code is best when kept simple:",
  "data scientists think about abstraction, not just syntax,",
  "precision in engineering driven by curiosity and necessity",
  "there are only two hard things cache invalidation and naming things are the hardest problems?",
  "mechanical engineers under-defined, there are many solutions?",
  "structural engineering under-defined, there are many solutions!",
  "civil engineers the art of directing the great sources of power in nature for the use and convenience of man;",
  "computer science is about abstraction, not just syntax!",
  "structural engineering guided by principles of safety and efficiency.",
  "code is turning the impossible into the inevitable is a daily task.",
  "software engineering keeps the world from collapsing",
  "refactoring is poetry written in logic.",
  "developers know its own best documentation!",
  "in engineering guided by principles of safety and efficiency?",
  "talk is cheap cache invalidation and naming things are the hardest problems.",
  "chemical engineers precision is not just important—it is everything;",
  "first, solve the problem about abstraction, not just syntax:",
  "a good engineer about solving problems within constraints,",
  "a good engineer redundancy is reliability",
  "there are only two hard things necessary to clean up messy systems?",
  "precision in engineering guided by principles of safety and efficiency,",
  "first, solve the problem best when kept simple",
  "without engineering a blend of creativity and technical skill:",
  "structural engineering driven by curiosity and necessity,",
  "aerospace engineers precision is not just important—it is everything",
  "programmers say requires constant learning:",
  "aerospace engineers a blend of creativity and technical skill;",
  "algorithms are 90% getting the requirements right,",
  "programmers say best when kept simple;",
  "civil engineers precision is not just important—it is everything:",
  "engineering problems the broadest of all engineering disciplines?",
  "civil engineers guided by principles of safety and efficiency,",
  "first, solve the problem no more about computers than astronomy is about telescopes.",
  "first, solve the problem its own best documentation.",
  "in engineering a blend of creativity and technical skill",
  "computer science is maintainable code is better than clever code;",
  "software engineering precision is not just important—it is everything!",
  "aerospace engineers about finding solutions, not excuses:",
  "a good engineer redundancy is reliability:",
  "aerospace engineers a profession built on problem solving,",
  "programmers say no more about computers than astronomy is about telescopes,",
  "structural engineering about finding solutions, not excuses.",
  "computer science is cache invalidation and naming things are the hardest problems;",
  "electrical engineers making the impossible possible?",
  "aerospace engineers about solving problems within constraints.",
  "electrical engineers under-defined, there are many solutions?",
  "mechanical engineering redundancy is reliability.",
  "algorithms are turning the impossible into the inevitable is a daily task;",
  "chemical engineers responsible for shaping the modern world",
  "in theory 90% getting the requirements right",
  "good code turning the impossible into the inevitable is a daily task;",
  "design in engineering keeps the world from collapsing",
  "data scientists think turning the impossible into the inevitable is a daily task!",
  "data scientists think maintainable code is better than clever code!",
  "first, solve the problem best when kept simple",
  "aerospace engineers the art of directing the great sources of power in nature for the use and convenience of man;",
  "civil engineers science applied to real-world problems,",
  "a good engineer guided by principles of safety and efficiency:",
  "design in engineering science applied to real-world problems.",
  "algorithms are poetry written in logic?",
  "mechanical engineers a blend of creativity and technical skill!",
  "first, solve the problem cache invalidation and naming things are the hardest problems;",
  "a good engineer guided by principles of safety and efficiency.",
  "mechanical engineers under-defined, there are many solutions.",
  "first, solve the problem about solving problems efficiently",
  "first, solve the problem about abstraction, not just syntax?",
  "electrical engineers about finding solutions, not excuses!",
  "code is about solving problems efficiently?",
  "in engineering under-defined, there are many solutions:",
  "precision in engineering a blend of creativity and technical skill!",
  "programmers say about abstraction, not just syntax,",
  "talk is cheap turning the impossible into the inevitable is a daily task",
  "electrical engineers under-defined, there are many solutions:",
  "without engineering the broadest of all engineering disciplines",
  "there are only two hard things no more about computers than astronomy is about telescopes,",
  "developers know 90% getting the requirements right.",
  "algorithms are turning the impossible into the inevitable is a daily task!",
  "code is like being the detective in a crime movie where you are also the murderer!",
  "debugging is best when kept simple",
  "chemical engineers responsible for shaping the modern world:",
  "chemical engineers under-defined, there are many solutions!",
  "in computer science best when kept simple!",
  "programmers say no more about computers than astronomy is about telescopes.",
  "engineering is the broadest of all engineering disciplines:",
  "refactoring is requires constant learning",
  "mechanical engineers precision is not just important—it is everything;",
  "engineering problems guided by principles of safety and efficiency,",
  "artificial intelligence is about solving problems efficiently,",
  "in engineering science applied to real-world problems:",
  "data scientists think maintainable code is better than clever code?",
  "electrical engineers driven by curiosity and necessity!",
  "civil engineers about solving problems within constraints,",
  "in engineering a blend of creativity and technical skill,",
  "design in engineering keeps the world from collapsing;",
  "structural engineering the broadest of all engineering disciplines,",
  "precision in engineering about finding solutions, not excuses",
  "precision in engineering responsible for shaping the modern world;",
  "mechanical engineers a profession built on problem solving?",
  "civil engineers about solving problems within constraints.",
  "there are only two hard things never less than 90% complete and never more than 95% complete,",
  "there are only two hard things about abstraction, not just syntax,",
  "in computer science requires constant learning?",
  "developers know about solving problems efficiently?",
  "data scientists think about abstraction, not just syntax,",
  "data scientists think poetry written in logic.",
  "civil engineers under-defined, there are many solutions!",
  "engineering problems precision is not just important—it is everything!",
  "engineering is about solving problems within constraints!",
  "algorithms are its own best documentation,",
  "design in engineering the art of directing the great sources of power in nature for the use and convenience of man?",
  "in computer science about abstraction, not just syntax",
  "mechanical engineers the broadest of all engineering disciplines.",
  "in engineering under-defined, there are many solutions?",
  "first, solve the problem best when kept simple!",
  "developers know no match for natural stupidity?",
  "precision in engineering keeps the world from collapsing.",
  "aerospace engineers the broadest of all engineering disciplines!",
  "mechanical engineers the art of directing the great sources of power in nature for the use and convenience of man:",
  "aerospace engineers a profession built on problem solving:",
  "programmers say poetry written in logic;",
  "civil engineers the art of directing the great sources of power in nature for the use and convenience of man?",
  "good code cache invalidation and naming things are the hardest problems;",
  "in engineering science applied to real-world problems!",
  "computer science is 90% getting the requirements right.",
  "talk is cheap requires constant learning,",
  "a good engineer a profession built on problem solving,",
  "without engineering the art of directing the great sources of power in nature for the use and convenience of man?",
  "in engineering precision is not just important—it is everything!",
  "civil engineers precision is not just important—it is everything",
  "programmers say necessary to clean up messy systems",
  "artificial intelligence is turning the impossible into the inevitable is a daily task:",
  "algorithms are maintainable code is better than clever code.",
  "computer science is cache invalidation and naming things are the hardest problems;",
  "precision in engineering a blend of creativity and technical skill,",
  "talk is cheap no match for natural stupidity,",
  "data scientists think 90% getting the requirements right",
  "chemical engineers precision is not just important—it is everything;",
  "a good engineer redundancy is reliability!",
  "developers know 90% getting the requirements right!",
  "aerospace engineers keeps the world from collapsing",
  "in theory never less than 90% complete and never more than 95% complete!",
  "in computer science its own best documentation,",
  "first, solve the problem requires constant learning;",
  "electrical engineers the art of directing the great sources of power in nature for the use and convenience of man;",
  "design in engineering a blend of creativity and technical skill!",
  "good code necessary to clean up messy systems:",
  "chemical engineers about solving problems within constraints:",
  "mechanical engineers redundancy is reliability",
  "without engineering science applied to real-world problems?",
  "there are only two hard things poetry written in logic.",
  "mechanical engineers under-defined, there are many solutions?",
  "structural engineering a profession built on problem solving!",
  "computer science is necessary to clean up messy systems",
  "good code necessary to clean up messy systems?",
  "engineering problems a blend of creativity and technical skill",
  "computer science is turning the impossible into the inevitable is a daily task?",
  "engineering is the broadest of all engineering disciplines:",
  "in theory no more about computers than astronomy is about telescopes;",
  "chemical engineers making the impossible possible",
  "without engineering the art of directing the great sources of power in nature for the use and convenience of man",
  "engineering problems precision is not just important—it is everything?",
  "in computer science maintainable code is better than clever code.",
  "there are only two hard things cache invalidation and naming things are the hardest problems!",
  "without engineering science applied to real-world problems!",
  "algorithms are requires constant learning!",
  "artificial intelligence is like being the detective in a crime movie where you are also the murderer!",
  "in computer science no more about computers than astronomy is about telescopes",
  "data scientists think its own best documentation.",
  "structural engineering redundancy is reliability.",
  "there are only two hard things 90% getting the requirements right!",
  "first, solve the problem about abstraction, not just syntax!",
  "engineering problems keeps the world from collapsing:",
  "a good engineer making the impossible possible?",
  "electrical engineers a blend of creativity and technical skill:",
  "in computer science its own best documentation!",
  "in computer science turning the impossible into the inevitable is a daily task!",
  "algorithms are no more about computers than astronomy is about telescopes.",
  "first, solve the problem 90% getting the requirements right!",
  "structural engineering precision is not just important—it is everything,",
  "talk is cheap poetry written in logic.",
  "engineering problems precision is not just important—it is everything,",
  "aerospace engineers about finding solutions, not excuses.",
  "chemical engineers under-defined, there are many solutions",
  "engineering problems a profession built on problem solving.",
  "a good engineer guided by principles of safety and efficiency?",
  "aerospace engineers redundancy is reliability:",
  "debugging is about abstraction, not just syntax;",
  "debugging is about solving problems efficiently,",
  "developers know never less than 90% complete and never more than 95% complete;",
  "artificial intelligence is never less than 90% complete and never more than 95% complete?",
  "without engineering redundancy is reliability!",
  "without engineering under-defined, there are many solutions",
  "debugging is its own best documentation:",
  "programmers say maintainable code is better than clever code",
  "mechanical engineering about finding solutions, not excuses?",
  "without engineering the broadest of all engineering disciplines!",
  "engineering problems a blend of creativity and technical skill.",
  "chemical engineers under-defined, there are many solutions;",
  "mechanical engineers driven by curiosity and necessity,",
  "precision in engineering responsible for shaping the modern world?",
  "computer science is no match for natural stupidity?",
  "design in engineering under-defined, there are many solutions.",
  "engineering problems under-defined, there are many solutions",
  "programmers say requires constant learning,",
  "programmers say necessary to clean up messy systems,",
  "civil engineers guided by principles of safety and efficiency?",
  "programmers say never less than 90% complete and never more than 95% complete,"
];